server:
  shutdown: graceful
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  main:
    banner-mode: off
  application:
    name: ikeyit-allinone
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  autoconfigure:
    exclude: net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration
