CREATE TABLE system_role
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(64)    NOT NULL,
    realm_type     VARCHAR(32)    NOT NULL,
    permission_ids JSON           NOT NULL,
    default_role   BOOLEAN        NOT NULL DEFAULT FALSE,
    supreme        BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);

CREATE TABLE permission
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(64)    NOT NULL,
    group_id    BIGINT         NOT NULL,
    realm_type  VARCHAR(32)    NOT NULL,
    description VARCHAR(255)   NOT NULL,
    created_at  TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX permission_idx_realm_type ON permission (realm_type);


CREATE TABLE permission_group
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255)   NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);