CREATE TABLE org
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64)    NOT NULL,
    picture VARCHAR(256)    NOT NULL,
    created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);


CREATE TABLE member
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL,
    display_name VARCHAR(64)    NOT NULL,
    status       SMALLINT       NOT NULL,
    created_at   TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX member_idx_user_id ON member (user_id);

CREATE TABLE role_binding
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT         NOT NULL,
    role_id    BIGINT         NOT NULL,
    role_type  SMALLINT       NOT NULL,
    realm_id   BIGINT         NOT NULL DEFAULT '0',
    realm_type VARCHAR(32)    NOT NULL,
    created_at TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX role_binding_idx_user_id_role_id_realm_id_realm_type ON role_binding (user_id, role_id, role_type, realm_id, realm_type);

CREATE TABLE custom_role
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(64)    NOT NULL,
    realm_id       BIGINT         NOT NULL DEFAULT '0',
    realm_type     VARCHAR(32)    NOT NULL,
    permission_ids JSON           NOT NULL,
    created_at     TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ(3) NOT NULL DEFAULT NOW()
);
CREATE INDEX custom_role_idx_realm_id_realm_type ON custom_role (realm_id, realm_type);



CREATE TABLE domain_event
(
    event_id    UUID           NOT NULL,
    listener_id VARCHAR(255)   NOT NULL,
    event_type  VARCHAR(255)   NOT NULL,
    payload     JSON           NOT NULL,
    created_at  TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
    headers     JSON           NOT NULL,
    primary key (event_id, listener_id)
);
CREATE INDEX domain_event_idx_created_at ON domain_event (created_at);