CREATE TABLE foo
(
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    status     SMALLINT     NOT NULL,
    message    VARCHAR(255) NOT NULL,
    source     JSON,
    created_at TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT NOW()
);