server:
  port: 8081
  reactive:
    session:
      cookie:
        max-age: 24h
      timeout: 24h
  error:
    whitelabel:
      enabled: false

logging:
  level:
    com.ikeyit: debug
    org.springframework.cloud.gateway: trace
    org.springframework.security: trace

spring:
  cloud:
    gateway:
      default-filters:
        - AccessTokenRelay
        - LocaleRelay
        - RemoveRequestHeader=Set-Cookie
      routes:
        - id: admin-api-access
          uri: http://localhost:8080
          predicates:
            - Path=/admin/api/v1/access/**
  security:
    oauth2:
      client:
        registration:
         account:
            provider: account
            client-id: web-client
            client-name: web-client
            client-secret: secret
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/auth/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - roles
        provider:
          account:
            issuer-uri: https://localhost:6111
            user-info-uri: ""
  config:
    import: "optional:file:${user.home}/ikeyit-config/ikeyit-admin-gateway/"