rootProject.name = "ikeyit-classroom"
include("ikeyit-classroom-domain")
include("ikeyit-classroom-application")
include("ikeyit-classroom-infrastructure")
include("ikeyit-classroom-interfaces-allinone")
include("ikeyit-classroom-interfaces-api")
include("ikeyit-classroom-interfaces-grpc")
include("ikeyit-classroom-interfaces-consumer")
include("ikeyit-classroom-interfaces-job")
include("ikeyit-classroom-sdk")