server:
  shutdown: graceful
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true
    session:
      timeout: 1d
      cookie:
        name: SID

spring:
  main:
    banner-mode: off
  application:
    name: account-allinone
  profiles:
    active: dev
  lifecycle:
    timeout-per-shutdown-phase: 30s
  autoconfigure:
    exclude: net.devh.boot.grpc.server.autoconfigure.GrpcServerSecurityAutoConfiguration
  session:
    redis:
      flush-mode: on_save
      namespace: "account:session"
      repository-type: indexed
