logging:
  level:
    com.ikeyit: debug

spring:
  config:
    import: "optional:file:${user.home}/ikeyit-config/ikeyit-foo/"
  datasource:
    foo:
      url: jdbc:postgresql://postgresql-server:5432/foo?currentSchema=public&stringtype=unspecified
      username: ikeyit
      password: dev_pass
      cp:
        maximum-pool-size: 5
        minimum-idle: 2
        idle-timeout: 60000